%function importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 25-Sep-2023 15:33:24

% Import the file
%newData1 = load(~mat, fileToRead1);

% Create new variables in the base workspace from those fields.
%vars = fieldnames(newData1);
%for i = 1:length(vars)
    %assignin('base', vars{i}, newData1.(vars{i}));
%end

load("COVIDbyCounty.mat")
save("COVIDbyCounty.mat")

findgroups(CNTY_Census)